force-failure

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,9 +2,9 @@ name: Backend CI/CD
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    branches: [ main ]
+    branches: [main]
 
 jobs:
   build:
@@ -35,7 +35,11 @@ jobs:
       - name: Deploy to Render
         run: |
           # Save logs to deploy.log so we can email them if something breaks
-          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOKS }} 2>&1 | tee deploy.log
+          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }} 2>&1 | tee deploy.log
+
+          
+          echo "Intentionally failing deploy for testing"
+          exit 1
 
       - name: Upload deploy log
         if: failure()
@@ -47,7 +51,7 @@ jobs:
   notify:
     needs: deploy
     runs-on: ubuntu-latest
-    if: failure()   # run only if deploy job failed
+    if: failure() # run only if deploy job failed
     steps:
       - name: Download deploy log
         uses: actions/download-artifact@v4
